### ISSUE TITLE
Tui-go crashes when a label is too long.

### ISSUE THREAD

**Issue by Danik32** [marcusolsson/tui-go#12] opened 2017-04-09 09:13 UTC
Our good old friend "panic: Parameter is incorrect".
Also crashes Buttons, and probably other UI elements.
Strangely though, if the label is added after the program is loaded completely, it doesn't crash, but instead it tries to  draw it over other the border:
![cmd_2017-04-09_12-19-54](https://cloud.githubusercontent.com/assets/19243585/24836224/e8f26a4a-1d1e-11e7-9e65-3884fa3ef343.png)

**Comment by Danik32** [comment] 2017-04-09 09:14
Also Buttons, and probably other UI elements.

**Comment by Danik32** [comment] 2017-04-09 09:20
Strangely though, if the label is added after the program is loaded completely, it doesn't crash, but instead it tries to  draw it over other the border
![cmd_2017-04-09_12-19-54](https://cloud.githubusercontent.com/assets/19243585/24836224/e8f26a4a-1d1e-11e7-9e65-3884fa3ef343.png)

**Comment by marcusolsson** [comment] 2017-04-10 10:39
I'm a bit annoyed that I can't reproduce this or find where the error is defined. Seriously though, thanks for reporting these issues. I think the long-term solution to these issues is to mask any painting outside the bounds of the widget. I'm currently working on refactoring of the layout engine which I hope will take care of some of these problems.

**Comment by Danik32** [comment] 2017-04-10 17:27
No problem! I really like your work, and I am very happy to help :D
Yeah, masking any painting outside the bounds of the widget should help a lot.

**Comment by marcusolsson** [comment] 2017-04-29 13:55
I've committed some major changes that I hope will sort of a few of the issues. Could you try with the latest commit? Heads up though, I've changed how size policies work to match that of Qt, so it might screw up your existing layouts. Really sorry about this but I absolutely believe its for the better. I'm trying to emulate the way size policies work in Qt: http://doc.qt.io/qt-5/qsizepolicy.html#Policy-enum

Let me know if I can help you in any way.

**Comment by Danik32** [comment] 2017-04-29 14:07
Was checking out the commit just now :D
Testing shows that this issue is fixed.

**Comment by marcusolsson** [comment] 2017-04-29 14:52
Great to hear!

**Closed by marcusolsson** 2017-04-29 14:52 UTC
